dbus-launch: drop unused error
dbus-launch.c: In function ‘main’:
dbus-launch.c:844:13: error: unused variable ‘error’ [-Werror=unused-variable]
  844 |   DBusError error = DBUS_ERROR_INIT;
      |             ^~~~~

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>